version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_pln
    command: >
      sh -c "uvicorn apps.main:app --reload --workers 2 --host 0.0.0.0 --port 8090"
    volumes:
      - .:/code
    restart: on-failure
    ports:
      - "8090:8090"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_fast
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=postgres

volumes:
  postgres_data:
