name: Lint

on:
  push:
    branches: [ "prod" ]
    paths:
      - '*.py'
  pull_request:
    branches: [ "prod" ]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Lint with flake8
        id: flake8
        continue-on-error: true
        run: |
          flake8 . --count --max-complexity=15 --max-line-length=127 --statistics

      - name: Check if 'Lint with flake8' step failed
        if: steps.flake8.outcome != 'success'
        run: |
          echo "flake8 fails"
          exit 1
          